name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gosunilgo/mailman-ci-runner:latest
    - name: DockerHub login
      env:
        CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
      run: docker login -u="gosunilgo" -p="$CI_JOB_TOKEN"
    - name: Push the Docker image
      run: docker push gosunilgo/mailman-ci-runner:latest
